import numpy as np
from flask import Blueprint, jsonify
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from datetime import datetime

route_ml_bp = Blueprint('route_ml', __name__)
supabase = None  

def _parse_db_time(date_str, time_val):
    """Combines schedule_date and a raw time string into a comparable datetime object."""
    try:
        if not time_val or not date_str: return None
        # Clean potential trailing characters from the date
        clean_date = str(date_str).split('T')[0]
        time_str = str(time_val)[:8] 
        return datetime.strptime(f"{clean_date} {time_str}", "%Y-%m-%d %H:%M:%S")
    except Exception as e:
        print(f"Schedule parse error: {e}")
        return None

def _parse_iso_timestamp(timestamp_str):
    """Parses full ISO timestamps generated by actual_start/end_time."""
    try:
        if not timestamp_str: return None
        # 1. Replace the ISO 'T' with a standard space
        # 2. Split at '.' to remove fractional microseconds
        # 3. Split at '+' or 'Z' to remove timezone metadata
        clean_str = str(timestamp_str).replace('T', ' ').split('.')[0].split('+')[0].replace('Z', '')
        return datetime.strptime(clean_str, "%Y-%m-%d %H:%M:%S")
    except Exception as e:
        print(f"ISO parse error on {timestamp_str}: {e}")
        return None

@route_ml_bp.route('/api/routes/cluster', methods=['GET', 'POST'])
def cluster_route_delays():
    try:
        # 1. Fetch completed trips that have actual timestamp data
        trips_res = supabase.table('trip_schedule').select(
            'trip_id, route_name, schedule_date, departure_time, estimated_arrival_time, actual_start_time, actual_end_time'
        ).eq('trip_status', 'Completed').not_.is_('actual_start_time', 'null').not_.is_('actual_end_time', 'null').execute()
        
        raw_trips = trips_res.data or []
        if len(raw_trips) < 3:
            return jsonify({"success": True, "status": "Insufficient Data", "message": "Need at least 3 completed trips with timestamps to run clustering."}), 200

        features = []
        valid_trips = []

        # 2. Feature Engineering: Calculate Variances in Minutes
        for t in raw_trips:
            date_str = t.get('schedule_date')
            
            sched_dep = _parse_db_time(date_str, t.get('departure_time'))
            sched_arr = _parse_db_time(date_str, t.get('estimated_arrival_time'))
            act_dep = _parse_iso_timestamp(t.get('actual_start_time'))
            act_arr = _parse_iso_timestamp(t.get('actual_end_time'))

            if not all([sched_dep, sched_arr, act_dep, act_arr]):
                continue

            # Calculate delays in minutes
            dep_delay = (act_dep - sched_dep).total_seconds() / 60.0
            arr_delay = (act_arr - sched_arr).total_seconds() / 60.0
            trip_duration = (act_arr - act_dep).total_seconds() / 60.0

            if trip_duration <= 0: continue # Ignore bad data
            
            features.append([dep_delay, arr_delay, trip_duration])
            
            t['dep_delay'] = dep_delay
            t['arr_delay'] = arr_delay
            t['duration'] = trip_duration
            valid_trips.append(t)

        if len(features) < 3:
            return jsonify({"success": True, "status": "Insufficient Data", "message": "Valid timestamp math failed."}), 200

        X = np.array(features)
        
        # 3. K-Means Clustering (3 Clusters: Optimal, Departure Bottleneck, Transit Delay)
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)
        
        # Dynamically adjust clusters if dataset is very small
        n_clusters = min(3, len(X))
        kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
        labels = kmeans.fit_predict(X_scaled)

        # 4. Analyze Cluster Characteristics
        cluster_summaries = []
        for i in range(n_clusters):
            cluster_pts = X[labels == i]
            avg_dep = np.mean(cluster_pts[:, 0])
            avg_arr = np.mean(cluster_pts[:, 1])
            avg_dur = np.mean(cluster_pts[:, 2])

            # Dynamic Labelling based on math
            # Dynamic Labelling based on math
            if avg_dep > 120 or avg_arr < -120 or avg_arr > 120:
                label = "Data Anomaly / Outlier"
                desc = "Extreme time variance detected. Likely a manual data entry or AM/PM error."
            elif avg_arr > 30 and avg_dep <= 15:
                label = "Transit/Traffic Delay Risk"
                desc = "Trips leave on time but hit severe road delays."
            elif avg_dep > 15:
                label = "Departure Bottleneck Risk"
                desc = "Trips are consistently leaving the garage late."
            else:
                label = "Optimal Baseline"
                desc = "Trips operating within acceptable schedule variance."

            cluster_summaries.append({
                "cluster_id": i,
                "label": label,
                "description": desc,
                "count": len(cluster_pts),
                "avg_departure_delay_mins": round(avg_dep, 1),
                "avg_arrival_delay_mins": round(avg_arr, 1),
                "avg_duration_mins": round(avg_dur, 1)
            })

        # 5. Route-Specific Actionable Insights
        route_stats = {}
        for idx, t in enumerate(valid_trips):
            r_name = t['route_name']
            c_id = labels[idx]
            
            if r_name not in route_stats:
                route_stats[r_name] = {"delays": [], "clusters": []}
            route_stats[r_name]['delays'].append(t['arr_delay'])
            route_stats[r_name]['clusters'].append(c_id)

        recommendations = []
        for r_name, stats in route_stats.items():
            avg_delay = sum(stats['delays']) / len(stats['delays'])
            if avg_delay > 20:
                recommendations.append({
                    "route": r_name,
                    "insight": f"Averages {round(avg_delay)} mins late.",
                    "action": f"Adjust scheduled arrival time forward by {round(avg_delay/5)*5} minutes to reflect actual traffic conditions."
                })

        return jsonify({
            "success": True,
            "status": "Clustered",
            "total_evaluated": len(valid_trips),
            "clusters": cluster_summaries,
            "recommendations": recommendations
        }), 200

    except Exception as e:
        print(f"❌ Route Clustering ML Error: {e}")
        return jsonify({"success": False, "message": str(e)}), 500